mikecm1141/little-shop-redux

.rspec
app/controllers/little_shop_app.rb
app/models/merchant.rb
app/views/merchants/edit.erb
app/views/merchants/index.erb
app/views/merchants/show.erb
db/migrate/20180815231757_merchants.rb
db/schema.rb
spec/models/merchant_spec.rb
spec/spec_helper.rb

Adds some limited crud functionality for merchant

Merchant 1

---

Gemfile.lock
app/controllers/little_shop_app.rb
app/views/merchants/index.erb
app/views/merchants/new.erb
spec/features/user_sees_all_merchants_spec.rb
spec/spec_helper.rb

X Wrote Tests
X Implemented
X Reviewed
- [] Bug Fix
* description Wrote feature tests for merchant, adjusted .erb accordingly and added methods to controller.  
closes #
Link: https://media3.giphy.com/media/xT0xeJpnrWC4XWblEk/giphy.gif

View merchants

---

spec/features/user_views_new_merchant_page_spec.rb

X Wrote Tests
____ Implemented
X Reviewed
- [] New feature
- [] Bug Fix
-[X] Adds Tests
* description Adds tests for features on new merchant page
closes #
Link: 
This guy would be proud....
https://www.turing.io/sites/default/files/styles/graduate_full_profile/public/headshot-small.jpg?itok=bZoiM1y_

Feature test new merchant

---

app/controllers/little_shop_app.rb
app/views/merchants/show.erb
spec/features/user_views_edit_merchant_page_spec.rb
spec/features/user_views_new_merchant_page_spec.rb

X Wrote Tests
X Implemented
X Reviewed
- [] New feature
- [] Bug Fix
* description - TESTS and IMPLEMENTS edit merchant
closes #15
Link:

TESTS and IMPLEMENTS edit merchant

---

spec/features/user_views_edit_merchant_page_spec.rb
spec/features/user_views_show_merchant_page_spec.rb

X Wrote Tests
____ Implemented
X Reviewed
- [] New feature
- [] Bug Fix
* description
closes #16 
Link: https://www.shape.com/sites/shape.com/files/u929/birthday-celebrate.gif

TESTS show page for merchant

---

db/seeds.rb

x Implemented
x Reviewed
- [] Bug Fix
* description
closes #18
- [] I have fully tested my code
Link:  https://reactiongifs.me/wp-content/uploads/2013/10/i-wingman-successfully-leonardo-dicaprio.gif

IMPLEMENTS seed for merchant table

---

app/public/css/main.css
app/views/layout.erb
app/views/merchants/index.erb

x Implemented
____ Reviewed
- [] New feature
- [] Bug Fix
* description
closes #
- [] I have fully tested my code
Link: https://media.giphy.com/media/3oxHQp7uBnjhUZ4vp6/giphy.gif

Initial layout

---

db/migrate/20180818175331_items.rb
db/schema.rb

_X__ Implemented
_X_ Reviewed
- [] Bug Fix
* description ADDS item table and migration
closes # 
Link: 
https://gifer.com/i/OH5.gif

ADDS item table and migration

---

app/controllers/little_shop_app.rb
app/views/items/index.erb
spec/features/user_sees_all_items_spec.rb

X Wrote Tests
X Implemented
X Reviewed
- [] Bug Fix
* description
closes #22
Link: 
https://media2.giphy.com/media/g0uYMARbVT6BW/giphy.gif

Item feature testing

---

app/controllers/little_shop_app.rb
app/models/item.rb
app/models/merchant.rb
app/views/items/index.erb
app/views/items/new.erb
app/views/items/show.erb
spec/features/user_can_create_new_item_spec.rb
spec/features/user_sees_all_items_spec.rb
spec/models/item_spec.rb
spec/models/merchant_spec.rb

X Wrote Tests
X Implemented
X Reviewed
- [] Bug Fix
* description -finishes all tests/features for new item page
closes #23
closes #24
closes #25
Link: 
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjdqv34z_fcAhXs6oMKHauFA3cQjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fexplore%2Fhappy-face&psig=AOvVaw3Yj7j-_Lrf2BK_PvjNahja&ust=1534716851704840

Item feature testing 2

---

app/controllers/little_shop_app.rb
app/views/items/edit.erb
app/views/items/show.erb
spec/features/user_can_edit_item_spec.rb
spec/features/user_can_view_individual_item_spec.rb
spec/features/user_sees_all_items_spec.rb

X Wrote Tests
X Implemented
X Reviewed
- [] Bug Fix
* description - creates test and method for edit and delete functions for item
closes #26 
closes #27 closes #28  
Link: 
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwj_sY7F4_ncAhXBx4MKHUcPDrwQjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Ftired-gif-sleep-sleepy-Q42cpzgcUeZkA&psig=AOvVaw0-ZG_SQpN6Xx_mV6Mf8ox_&ust=1534790832140335

TESTS and IMPLEMENTS item edit and delete functionality

---

app/models/invoice.rb
app/models/merchant.rb
db/migrate/20180819220014_invoices.rb
db/schema.rb
spec/models/invoices_spec.rb

__X__ Wrote Tests
____ Reviewed
- [] The code will run locally
- [] Bug Fix
* description - creates table/test/class for invoice 
closes #
Link: 
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjnxsXLlPrcAhWI8oMKHYMgBU4QjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fcute-kitten-3GgKk4Bv58Mwg&psig=AOvVaw0IK8yZJUaDbbOcWBuPIsa0&ust=1534803993259771

ADDS invoice table, TESTS and VALIDATES invoice association validation

---

app/models/invoice_item.rb
db/migrate/20180819220012_invoice_items.rb
db/schema.rb
spec/models/invoice_item_spec.rb

____ Reviewed
- [] Bug Fix
* description ADDS invoice item migration, waiting on invoice class to be created
closes #
Link: 
https://media1.tenor.com/images/a1cd7d1b0292ab204a5a9074d9b0f81b/tenor.gif?itemid=5641125

ADDS invoice item migration

---

app/public/main.css
app/views/merchants/edit.erb
app/views/merchants/new.erb
app/views/merchants/show.erb
spec/features/user_views_edit_merchant_page_spec.rb
spec/features/user_views_new_merchant_page_spec.rb

x Implemented
____ Reviewed
- [] Bug Fix
* description
Implements design and styling for new merchant, edit merchant, and show merchant
closes #
Link:  https://media.giphy.com/media/Cwmni9chqYZgc/giphy.gif

Style work2

---

app/controllers/little_shop_app.rb
app/views/invoices/index.erb
spec/features/user_sees_all_invoices_spec.rb
spec/models/invoices_spec.rb

__X__ Wrote Tests
____ Reviewed
- [] Bug Fix
* description - TESTS and IMPLEMENTS features for invoices index page
closes #40 
Link: 
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwin15eYovrcAhVD64MKHV0JC3UQjRx6BAgBEAU&url=https%3A%2F%2Fgfycat.com%2Fgifs%2Fsearch%2Ftest&psig=AOvVaw3QA_O7ze1jVZ7hRJ7NInn3&ust=1534807649036129

Invoice validations

---

app/controllers/little_shop_app.rb
app/views/invoices/show.erb
spec/features/user_sees_all_invoices_spec.rb
spec/features/user_views_show_invoice_page_spec.rb

__X__ Wrote Tests
____ Reviewed
- [] Bug Fix
* description - TESTS and IMPLEMENTS show features for invoices
closes #41 
- [] This broke nothing
- [] My code has no unused/commented out code
Link: https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwi0gKmSqfzcAhWMxIMKHTRoALQQjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fexplore%2Fconfused&psig=AOvVaw1I1yC-_aWOBSdBQHs2TzS1&ust=1534878235611499

TESTS and IMPLEMENTS show features for invoices

---

app/controllers/little_shop_app.rb
app/models/invoice.rb
app/models/invoice_item.rb
app/views/invoices/dashboard.erb
app/views/invoices/edit.erb
app/views/invoices/show.erb
db/seeds.rb
spec/features/user_can_edit_invoice_spec.rb
spec/features/user_sees_all_invoices_spec.rb

_X___ Wrote Tests
_X___ Implemented
____ Reviewed
- [] Bug Fix
* description - TESTS and IMPLEMENTS edit button functionality for invoice. ADDS invoice dashboard and 2 of 3 outputs
closes #43 
closes #44 
closes #45 
closes #46
Link: 
https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwjcg4_Jxv7cAhWPxIMKHYQXC2EQjRx6BAgBEAU&url=https%3A%2F%2Ftenor.com%2Fview%2Fcelebration-benedict-cumberbatch-jimmy-fallon-gif-7241283&psig=AOvVaw1bhV_ks8J1x2CIoCCZQxmP&ust=1534954853969601

Invoice edit

---

app/models/invoice_item.rb
app/models/item.rb
app/views/invoices/index.erb
app/views/invoices/show.erb
app/views/merchants/show.erb
db/migrate/20180819220012_invoice_items.rb
db/schema.rb
spec/features/user_can_create_new_item_spec.rb
spec/features/user_can_edit_invoice_spec.rb
spec/features/user_can_edit_item_spec.rb
spec/features/user_can_view_individual_item_spec.rb
spec/features/user_sees_all_invoices_spec.rb
spec/features/user_sees_all_items_spec.rb
spec/features/user_views_show_invoice_page_spec.rb
spec/features/user_views_show_merchant_page_spec.rb

__X_ Wrote Tests
__X_ Implemented
__X_ Reviewed
* description TEST and IMPLEMENTS invoice show page information
closes #42 
Link: https://media0.giphy.com/media/yoJC2K6rCzwNY2EngA/giphy.gif

Invoice shows invoice items

---

app/controllers/little_shop_app.rb
app/models/merchant.rb
app/views/merchants/dashboard.erb
spec/features/user_views_show_merchant_dashboard_spec.rb
spec/models/merchant_spec.rb

_X__ Wrote Tests
_X__ Implemented
_X__ Reviewed
- [] Bug Fix
* description TESTS and IMPLEMENTS merchant dashboard and methods
closes #
Link: https://media.tenor.com/images/51b6a1af7f91bab859445157bcb6ba7a/tenor.gif

TESTS and IMPLEMENTS merchant dashboard and methods

---

app/controllers/little_shop_app.rb
app/models/invoice.rb
app/models/item.rb
app/views/invoices/dashboard.erb
app/views/items/dashboard.erb
data/items.csv
spec/models/invoices_spec.rb
spec/models/item_spec.rb

___X_ Wrote Tests
____ Reviewed
- [] Bug Fix
* description- TESTS and iMPLEMENTS methods for invoice and items dashboard
closes #
Link: https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwj6sb27rP_cAhVp_IMKHQH2ANsQjRx6BAgBEAU&url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fthe-office-steve-carell-michael-scott-dsKnRuALlWsZG&psig=AOvVaw3SXK4Y0ilT8jWGbG1DD1tq&ust=1534982193121307

TESTS and IMPLEMENTS methods for invoice and items dashboard

---

app/public/main.css
app/views/invoices/edit.erb
app/views/invoices/index.erb
app/views/invoices/show.erb
app/views/items/edit.erb
app/views/items/index.erb
app/views/layout.erb
app/views/merchants/edit.erb
app/views/merchants/show.erb
app/views/welcome.erb
db/seeds.rb
spec/features/user_can_edit_invoice_spec.rb
spec/features/user_views_show_invoice_page_spec.rb

x Implemented
____ Reviewed
- [] Bug Fix
* description Adds styling for invoices
closes #
Link:

Style work 7
